#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.106.83.21:3306/tuandui?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 5201314Zy.
      max-active: 20
      max-wait: 5000

  ###############Redis 配置
  redis:
    database: 0
    timeout: 6000
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        max-active: 8
        min-idle: 1
    host: 47.106.83.21
    port: 6379
    password: Redis_123


  servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 10MB

  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#修改端口号为8088
server:
  port: 8088

shiro:
  session-timeout: 1800000
  cookie-timeout: 1800000
  anon-url: /user/addUser
  login-url: /login
  success-url: /index
  unauthorized-url: /unauthorized


